server:
  port: 8090
spring:
  application:
    name: lagou-service-deliver
#  autoconfigure:
#    exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 172.30.156.97:8848 #nacos server配置地址
eureka:
  client:
    service-url:
      defaultZone: http://EurekaServerA:8761/eureka, http://EurekaServerB:8762/eureka
    registry-fetch-interval-seconds: 30 #30s从注册中心拉一次服务列表
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT
    lease-renewal-interval-in-seconds: 30 #30s向注册中心续约(续约)
    lease-expiration-duration-in-seconds: 90 #90s未续约将移除
lagou-service-resume:
  ribbon:
    OkToRetryOnAllOperations: true
    ####根据如上配置，当访问到故障请求的时候，它会再尝试访问⼀次当前实例（次数由MaxAutoRetries配置），
    ####如果不⾏，就换⼀个实例进⾏访问，如果还不⾏，再换⼀次实例访问（更换次数由MaxAutoRetriesNextServer配置），
    ####如果依然不⾏，返回失败信息。
    MaxAutoRetries: 0 #对当前选中实例重试次数，不包括第⼀次调⽤
    MaxAutoRetriesNextServer: 0 #切换实例的重试次数
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#配置方式设置熔断
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        forceOpen: false
#        errorThresholdPercentage: 50 #错误率 默认50%
#        sleepWindowInMillseconds: 3000 #熔断后休眠时常  默认5s
#        requestVolumeThreshold: 2 #熔断出发最小请求次数 默认是20
#      execution:
#        isolation:
#          thread:
#            timeoutInMillseconds: 2000 #熔断超时设置 默认1s

#springboot暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#开启feign的熔断功能
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true  #开启请求压缩
      mime-types: text/html,application/xml,application/json  #设置压缩的数据类型，此处还是默认值
      min-request-size: 2048 #设置触发压缩的大小下限 此处也是默认值
    response:
      enabled: true #开启响应压缩
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
    ##########################################Hystrix的超时时⻓设置
            timeoutInMilliseconds: 15000

#配置日志级别
logging:
  level:
    com.xu.ite.ResumeFeighClient: debug